services:
  api_gateway:
    build: api_gateway
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - USERS_SERVICE_URL=http://service_users:3001
      - ORDERS_SERVICE_URL=http://service_orders:3002
      - DELIVERY_SERVICE_URL=http://service_delivery:3003
    depends_on:
      - service_users
      - service_orders
      - service_delivery
    networks:
      - app-network

  service_users:
    build: service_users
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=postgresql://user:password@db_users:5432/users_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db_users
      - redis
    networks:
      - app-network

  service_orders:
    build: service_orders
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - DATABASE_URL=postgresql://user:password@db_orders:5432/orders_db
      - REDIS_URL=redis://redis:6379
      - DELIVERY_SERVICE_URL=http://service_delivery:3003
    depends_on:
      - db_orders
      - redis
    networks:
      - app-network

  service_delivery:
    build: service_delivery
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
      - DATABASE_URL=postgresql://user:password@db_delivery:5432/delivery_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db_delivery
      - redis
    networks:
      - app-network

  db_users:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    volumes:
      - postgres_data_users:/var/lib/postgresql/data
    networks:
      - app-network

  db_orders:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    volumes:
      - postgres_data_orders:/var/lib/postgresql/data
    networks:
      - app-network

  db_delivery:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: delivery_db
    volumes:
      - postgres_data_delivery:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  postgres_data_users:
  postgres_data_orders:
  postgres_data_delivery:

networks:
  app-network:
    driver: bridge